from turtle import *
#bottom circle
title('snowman')
turtle = Turtle()
turtle.up()
turtle.goto(0,-250)
turtle.down()
turtle.color('black')
turtle.width(width=5)
turtle.fill(1)
turtle.fill(0)
turtle.circle(120)
turtle.hideturtle()
#center circle
turtle = Turtle()
turtle.up()
turtle.goto(0,-10)
turtle.down()
turtle.color('black')
turtle.width(width=5)
turtle.fill(1)
turtle.fill(0)
turtle.circle(90)
turtle.hideturtle()
#top circle
turtle = Turtle()
turtle.up()
turtle.goto(0,170)
turtle.down()
turtle.color('black')
turtle.width(width=5)
turtle.fill(1)
turtle.fill(0)
turtle.circle(60)
turtle.hideturtle()
